name: Build & Test

on:
  push:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node v12
        uses: actions/setup-node@master
        with:
          node-version: 12
      - name: Install dependencies
        run: npm ci
      - name: Source code artifact
        uses: actions/upload-artifact@v2
        with:
          name: source-artifact
          path: |
            ./**/*     
  
  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Download source artifact
        uses: actions/download-artifact@v2
        with:
          name: source-artifact
      - name: Lint
        run: npm run lint
  
  tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Download source artifact
        uses: actions/download-artifact@v2
        with:
          name: source-artifact
      - name: Unit Test
        run: npm run test:cov
        env:
          CI: true
      - name: E2E Test
        run: npm run test:e2e
        env:
          CI: true
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Download source artifact
        uses: actions/download-artifact@v2
        with:
          name: source-artifact
      - name: Build
        run: npm run build
      - name: Build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: |
            ./**/*
      
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, tests, build]
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
      - name: Deploy to Heroku
        run: git push -f https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git origin/master:master
